trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: 'Release'

steps:

# Install .NET 8 SDK
- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

# Restore NuGet packages
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '**/*.sln'

# Build Solution
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    arguments: '--configuration $(BuildConfiguration)'

# Install Playwright Browsers
- script: |
    dotnet tool install --global Microsoft.Playwright.CLI
    playwright install
  displayName: 'Install Playwright Browsers'

# Execute NUnit Tests
- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: 'test'
    projects: '**/*.sln'
    arguments: '--configuration $(BuildConfiguration) --logger trx'

# Publish Test Results
- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  condition: always()
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    mergeTestResults: true
    failTaskOnFailedTests: false

# Publish Automation Reports (Extent Report, Screenshots, Videos)
- task: PublishBuildArtifacts@1
  displayName: 'Publish Automation Reports'
  condition: always()
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'TestResults'
    publishLocation: 'Container'